{% set name = "dsms-sdk" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dsms_sdk-{{ version }}.tar.gz
  sha256: 380cdd5f9d938ad8ca27aacc783c7c4e2a5bc3b7c19c8515e15a4274204e89b7
  patches:
    - cache.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - oyaml ==1
    - click >=8,<9
    - html5lib >=1,<2
    - python-dotenv
    - pyyaml >=6,<7
    - qrcode-artistic >=3,<4
    - segno >=1.6,<1.7
    - python >={{ python_min }}
    - pandas >=2,<3
    - pydantic >=2,<3
    - pydantic-settings
    - rdflib >=6,<7
    - requests

test:
  imports:
    - dsms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MI-FraunhoferIWM/dsms-python-sdk
  summary: Python SDK core-package for working with the Dataspace Management System (DSMS).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
