{% set name = "dsms-sdk" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dsms_sdk-{{ version }}.tar.gz
  sha256: 219c8bf659ea300231be2303d5c5534dc722ad71bdd810fbf65a6d873b88096d
  patches:
    - cache.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - lru-cache <1
    - click >=8,<9
    - html5lib >=1,<2
    - python-dotenv
    - pyyaml >=6,<7
    - qrcode-artistic >=3,<4
    - segno >=1.6,<1.7
    - python >=3.8
    - pandas >=2,<3
    - pydantic >=2
    - pydantic-settings
    - rdflib >=6,<7
    - requests

test:
  imports:
    - dsms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MI-FraunhoferIWM/dsms-python-sdk
  summary: Python SDK core-package for working with the Dataspace Management System (DSMS).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
